// Code generated by ent, DO NOT EDIT.

package usertoken

import (
	"pr-reviewer-ai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserToken {
	return predicate.UserToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserToken {
	return predicate.UserToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserToken {
	return predicate.UserToken(sql.FieldLTE(FieldID, id))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldToken, v))
}

// WebURL applies equality check predicate on the "web_url" field. It's identical to WebURLEQ.
func WebURL(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldWebURL, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldProjectID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.UserToken {
	return predicate.UserToken(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.UserToken {
	return predicate.UserToken(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldContainsFold(FieldToken, v))
}

// WebURLEQ applies the EQ predicate on the "web_url" field.
func WebURLEQ(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldWebURL, v))
}

// WebURLNEQ applies the NEQ predicate on the "web_url" field.
func WebURLNEQ(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldNEQ(FieldWebURL, v))
}

// WebURLIn applies the In predicate on the "web_url" field.
func WebURLIn(vs ...string) predicate.UserToken {
	return predicate.UserToken(sql.FieldIn(FieldWebURL, vs...))
}

// WebURLNotIn applies the NotIn predicate on the "web_url" field.
func WebURLNotIn(vs ...string) predicate.UserToken {
	return predicate.UserToken(sql.FieldNotIn(FieldWebURL, vs...))
}

// WebURLGT applies the GT predicate on the "web_url" field.
func WebURLGT(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldGT(FieldWebURL, v))
}

// WebURLGTE applies the GTE predicate on the "web_url" field.
func WebURLGTE(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldGTE(FieldWebURL, v))
}

// WebURLLT applies the LT predicate on the "web_url" field.
func WebURLLT(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldLT(FieldWebURL, v))
}

// WebURLLTE applies the LTE predicate on the "web_url" field.
func WebURLLTE(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldLTE(FieldWebURL, v))
}

// WebURLContains applies the Contains predicate on the "web_url" field.
func WebURLContains(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldContains(FieldWebURL, v))
}

// WebURLHasPrefix applies the HasPrefix predicate on the "web_url" field.
func WebURLHasPrefix(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldHasPrefix(FieldWebURL, v))
}

// WebURLHasSuffix applies the HasSuffix predicate on the "web_url" field.
func WebURLHasSuffix(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldHasSuffix(FieldWebURL, v))
}

// WebURLIsNil applies the IsNil predicate on the "web_url" field.
func WebURLIsNil() predicate.UserToken {
	return predicate.UserToken(sql.FieldIsNull(FieldWebURL))
}

// WebURLNotNil applies the NotNil predicate on the "web_url" field.
func WebURLNotNil() predicate.UserToken {
	return predicate.UserToken(sql.FieldNotNull(FieldWebURL))
}

// WebURLEqualFold applies the EqualFold predicate on the "web_url" field.
func WebURLEqualFold(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldEqualFold(FieldWebURL, v))
}

// WebURLContainsFold applies the ContainsFold predicate on the "web_url" field.
func WebURLContainsFold(v string) predicate.UserToken {
	return predicate.UserToken(sql.FieldContainsFold(FieldWebURL, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int64) predicate.UserToken {
	return predicate.UserToken(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.UserToken {
	return predicate.UserToken(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.UserToken {
	return predicate.UserToken(sql.FieldNotNull(FieldProjectID))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserToken {
	return predicate.UserToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.UserToken {
	return predicate.UserToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.UserToken {
	return predicate.UserToken(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserToken) predicate.UserToken {
	return predicate.UserToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserToken) predicate.UserToken {
	return predicate.UserToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserToken) predicate.UserToken {
	return predicate.UserToken(sql.NotPredicates(p))
}
