// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReviewLogsColumns holds the columns for the "review_logs" table.
	ReviewLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "mr_id", Type: field.TypeInt},
		{Name: "project_id", Type: field.TypeString},
		{Name: "comment", Type: field.TypeString},
		{Name: "reviewed_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ReviewLogsTable holds the schema information for the "review_logs" table.
	ReviewLogsTable = &schema.Table{
		Name:       "review_logs",
		Columns:    ReviewLogsColumns,
		PrimaryKey: []*schema.Column{ReviewLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "review_logs_users_review_logs",
				Columns:    []*schema.Column{ReviewLogsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "gitlab_user_id", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserTokensColumns holds the columns for the "user_tokens" table.
	UserTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "web_url", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
	}
	// UserTokensTable holds the schema information for the "user_tokens" table.
	UserTokensTable = &schema.Table{
		Name:       "user_tokens",
		Columns:    UserTokensColumns,
		PrimaryKey: []*schema.Column{UserTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tokens_users_token",
				Columns:    []*schema.Column{UserTokensColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReviewLogsTable,
		UsersTable,
		UserTokensTable,
	}
)

func init() {
	ReviewLogsTable.ForeignKeys[0].RefTable = UsersTable
	UserTokensTable.ForeignKeys[0].RefTable = UsersTable
}
