// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pr-reviewer-ai/ent/reviewlog"
	"pr-reviewer-ai/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ReviewLog is the model entity for the ReviewLog schema.
type ReviewLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MrID holds the value of the "mr_id" field.
	MrID int `json:"mr_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReviewLogQuery when eager-loading is set.
	Edges        ReviewLogEdges `json:"edges"`
	user_id      *int
	selectValues sql.SelectValues
}

// ReviewLogEdges holds the relations/edges for other nodes in the graph.
type ReviewLogEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReviewLogEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReviewLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reviewlog.FieldID, reviewlog.FieldMrID:
			values[i] = new(sql.NullInt64)
		case reviewlog.FieldProjectID, reviewlog.FieldComment:
			values[i] = new(sql.NullString)
		case reviewlog.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		case reviewlog.ForeignKeys[0]: // user_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReviewLog fields.
func (_m *ReviewLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reviewlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case reviewlog.FieldMrID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mr_id", values[i])
			} else if value.Valid {
				_m.MrID = int(value.Int64)
			}
		case reviewlog.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case reviewlog.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case reviewlog.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		case reviewlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_id", value)
			} else if value.Valid {
				_m.user_id = new(int)
				*_m.user_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReviewLog.
// This includes values selected through modifiers, order, etc.
func (_m *ReviewLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ReviewLog entity.
func (_m *ReviewLog) QueryOwner() *UserQuery {
	return NewReviewLogClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this ReviewLog.
// Note that you need to call ReviewLog.Unwrap() before calling this method if this ReviewLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReviewLog) Update() *ReviewLogUpdateOne {
	return NewReviewLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReviewLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReviewLog) Unwrap() *ReviewLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReviewLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReviewLog) String() string {
	var builder strings.Builder
	builder.WriteString("ReviewLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("mr_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MrID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReviewLogs is a parsable slice of ReviewLog.
type ReviewLogs []*ReviewLog
