// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pr-reviewer-ai/ent/predicate"
	"pr-reviewer-ai/ent/reviewlog"
	"pr-reviewer-ai/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReviewLogUpdate is the builder for updating ReviewLog entities.
type ReviewLogUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewLogMutation
}

// Where appends a list predicates to the ReviewLogUpdate builder.
func (_u *ReviewLogUpdate) Where(ps ...predicate.ReviewLog) *ReviewLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMrID sets the "mr_id" field.
func (_u *ReviewLogUpdate) SetMrID(v int) *ReviewLogUpdate {
	_u.mutation.ResetMrID()
	_u.mutation.SetMrID(v)
	return _u
}

// SetNillableMrID sets the "mr_id" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableMrID(v *int) *ReviewLogUpdate {
	if v != nil {
		_u.SetMrID(*v)
	}
	return _u
}

// AddMrID adds value to the "mr_id" field.
func (_u *ReviewLogUpdate) AddMrID(v int) *ReviewLogUpdate {
	_u.mutation.AddMrID(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ReviewLogUpdate) SetProjectID(v string) *ReviewLogUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableProjectID(v *string) *ReviewLogUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewLogUpdate) SetComment(v string) *ReviewLogUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableComment(v *string) *ReviewLogUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ReviewLogUpdate) SetOwnerID(id int) *ReviewLogUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ReviewLogUpdate) SetOwner(v *User) *ReviewLogUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ReviewLogMutation object of the builder.
func (_u *ReviewLogUpdate) Mutation() *ReviewLogMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ReviewLogUpdate) ClearOwner() *ReviewLogUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewLogUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.owner"`)
	}
	return nil
}

func (_u *ReviewLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewlog.Table, reviewlog.Columns, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MrID(); ok {
		_spec.SetField(reviewlog.FieldMrID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMrID(); ok {
		_spec.AddField(reviewlog.FieldMrID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(reviewlog.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(reviewlog.FieldComment, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.OwnerTable,
			Columns: []string{reviewlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.OwnerTable,
			Columns: []string{reviewlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewLogUpdateOne is the builder for updating a single ReviewLog entity.
type ReviewLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewLogMutation
}

// SetMrID sets the "mr_id" field.
func (_u *ReviewLogUpdateOne) SetMrID(v int) *ReviewLogUpdateOne {
	_u.mutation.ResetMrID()
	_u.mutation.SetMrID(v)
	return _u
}

// SetNillableMrID sets the "mr_id" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableMrID(v *int) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetMrID(*v)
	}
	return _u
}

// AddMrID adds value to the "mr_id" field.
func (_u *ReviewLogUpdateOne) AddMrID(v int) *ReviewLogUpdateOne {
	_u.mutation.AddMrID(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ReviewLogUpdateOne) SetProjectID(v string) *ReviewLogUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableProjectID(v *string) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewLogUpdateOne) SetComment(v string) *ReviewLogUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableComment(v *string) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ReviewLogUpdateOne) SetOwnerID(id int) *ReviewLogUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ReviewLogUpdateOne) SetOwner(v *User) *ReviewLogUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ReviewLogMutation object of the builder.
func (_u *ReviewLogUpdateOne) Mutation() *ReviewLogMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ReviewLogUpdateOne) ClearOwner() *ReviewLogUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ReviewLogUpdate builder.
func (_u *ReviewLogUpdateOne) Where(ps ...predicate.ReviewLog) *ReviewLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewLogUpdateOne) Select(field string, fields ...string) *ReviewLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReviewLog entity.
func (_u *ReviewLogUpdateOne) Save(ctx context.Context) (*ReviewLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewLogUpdateOne) SaveX(ctx context.Context) *ReviewLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewLogUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.owner"`)
	}
	return nil
}

func (_u *ReviewLogUpdateOne) sqlSave(ctx context.Context) (_node *ReviewLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewlog.Table, reviewlog.Columns, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReviewLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewlog.FieldID)
		for _, f := range fields {
			if !reviewlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reviewlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MrID(); ok {
		_spec.SetField(reviewlog.FieldMrID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMrID(); ok {
		_spec.AddField(reviewlog.FieldMrID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(reviewlog.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(reviewlog.FieldComment, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.OwnerTable,
			Columns: []string{reviewlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.OwnerTable,
			Columns: []string{reviewlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReviewLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
