// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pr-reviewer-ai/ent/reviewlog"
	"pr-reviewer-ai/ent/schema"
	"pr-reviewer-ai/ent/user"
	"pr-reviewer-ai/ent/usertoken"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	reviewlogFields := schema.ReviewLog{}.Fields()
	_ = reviewlogFields
	// reviewlogDescReviewedAt is the schema descriptor for reviewed_at field.
	reviewlogDescReviewedAt := reviewlogFields[3].Descriptor()
	// reviewlog.DefaultReviewedAt holds the default value on creation for the reviewed_at field.
	reviewlog.DefaultReviewedAt = reviewlogDescReviewedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	usertokenFields := schema.UserToken{}.Fields()
	_ = usertokenFields
	// usertokenDescUpdatedAt is the schema descriptor for updated_at field.
	usertokenDescUpdatedAt := usertokenFields[2].Descriptor()
	// usertoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usertoken.DefaultUpdatedAt = usertokenDescUpdatedAt.Default.(func() time.Time)
	// usertoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usertoken.UpdateDefaultUpdatedAt = usertokenDescUpdatedAt.UpdateDefault.(func() time.Time)
}
