// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pr-reviewer-ai/ent/predicate"
	"pr-reviewer-ai/ent/user"
	"pr-reviewer-ai/ent/usertoken"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTokenUpdate is the builder for updating UserToken entities.
type UserTokenUpdate struct {
	config
	hooks    []Hook
	mutation *UserTokenMutation
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (_u *UserTokenUpdate) Where(ps ...predicate.UserToken) *UserTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *UserTokenUpdate) SetToken(v string) *UserTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableToken(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetWebURL sets the "web_url" field.
func (_u *UserTokenUpdate) SetWebURL(v string) *UserTokenUpdate {
	_u.mutation.SetWebURL(v)
	return _u
}

// SetNillableWebURL sets the "web_url" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableWebURL(v *string) *UserTokenUpdate {
	if v != nil {
		_u.SetWebURL(*v)
	}
	return _u
}

// ClearWebURL clears the value of the "web_url" field.
func (_u *UserTokenUpdate) ClearWebURL() *UserTokenUpdate {
	_u.mutation.ClearWebURL()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *UserTokenUpdate) SetProjectID(v int64) *UserTokenUpdate {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableProjectID(v *int64) *UserTokenUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *UserTokenUpdate) AddProjectID(v int64) *UserTokenUpdate {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *UserTokenUpdate) ClearProjectID() *UserTokenUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetLastEventID sets the "last_event_id" field.
func (_u *UserTokenUpdate) SetLastEventID(v int64) *UserTokenUpdate {
	_u.mutation.ResetLastEventID()
	_u.mutation.SetLastEventID(v)
	return _u
}

// SetNillableLastEventID sets the "last_event_id" field if the given value is not nil.
func (_u *UserTokenUpdate) SetNillableLastEventID(v *int64) *UserTokenUpdate {
	if v != nil {
		_u.SetLastEventID(*v)
	}
	return _u
}

// AddLastEventID adds value to the "last_event_id" field.
func (_u *UserTokenUpdate) AddLastEventID(v int64) *UserTokenUpdate {
	_u.mutation.AddLastEventID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenUpdate) SetUpdatedAt(v time.Time) *UserTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *UserTokenUpdate) SetOwnerID(id int) *UserTokenUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *UserTokenUpdate) SetOwner(v *User) *UserTokenUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (_u *UserTokenUpdate) Mutation() *UserTokenMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *UserTokenUpdate) ClearOwner() *UserTokenUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserToken.owner"`)
	}
	return nil
}

func (_u *UserTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(usertoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebURL(); ok {
		_spec.SetField(usertoken.FieldWebURL, field.TypeString, value)
	}
	if _u.mutation.WebURLCleared() {
		_spec.ClearField(usertoken.FieldWebURL, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(usertoken.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(usertoken.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(usertoken.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastEventID(); ok {
		_spec.SetField(usertoken.FieldLastEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastEventID(); ok {
		_spec.AddField(usertoken.FieldLastEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usertoken.OwnerTable,
			Columns: []string{usertoken.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usertoken.OwnerTable,
			Columns: []string{usertoken.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTokenUpdateOne is the builder for updating a single UserToken entity.
type UserTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTokenMutation
}

// SetToken sets the "token" field.
func (_u *UserTokenUpdateOne) SetToken(v string) *UserTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableToken(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetWebURL sets the "web_url" field.
func (_u *UserTokenUpdateOne) SetWebURL(v string) *UserTokenUpdateOne {
	_u.mutation.SetWebURL(v)
	return _u
}

// SetNillableWebURL sets the "web_url" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableWebURL(v *string) *UserTokenUpdateOne {
	if v != nil {
		_u.SetWebURL(*v)
	}
	return _u
}

// ClearWebURL clears the value of the "web_url" field.
func (_u *UserTokenUpdateOne) ClearWebURL() *UserTokenUpdateOne {
	_u.mutation.ClearWebURL()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *UserTokenUpdateOne) SetProjectID(v int64) *UserTokenUpdateOne {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableProjectID(v *int64) *UserTokenUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *UserTokenUpdateOne) AddProjectID(v int64) *UserTokenUpdateOne {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *UserTokenUpdateOne) ClearProjectID() *UserTokenUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetLastEventID sets the "last_event_id" field.
func (_u *UserTokenUpdateOne) SetLastEventID(v int64) *UserTokenUpdateOne {
	_u.mutation.ResetLastEventID()
	_u.mutation.SetLastEventID(v)
	return _u
}

// SetNillableLastEventID sets the "last_event_id" field if the given value is not nil.
func (_u *UserTokenUpdateOne) SetNillableLastEventID(v *int64) *UserTokenUpdateOne {
	if v != nil {
		_u.SetLastEventID(*v)
	}
	return _u
}

// AddLastEventID adds value to the "last_event_id" field.
func (_u *UserTokenUpdateOne) AddLastEventID(v int64) *UserTokenUpdateOne {
	_u.mutation.AddLastEventID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenUpdateOne) SetUpdatedAt(v time.Time) *UserTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *UserTokenUpdateOne) SetOwnerID(id int) *UserTokenUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *UserTokenUpdateOne) SetOwner(v *User) *UserTokenUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (_u *UserTokenUpdateOne) Mutation() *UserTokenMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *UserTokenUpdateOne) ClearOwner() *UserTokenUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the UserTokenUpdate builder.
func (_u *UserTokenUpdateOne) Where(ps ...predicate.UserToken) *UserTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTokenUpdateOne) Select(field string, fields ...string) *UserTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserToken entity.
func (_u *UserTokenUpdateOne) Save(ctx context.Context) (*UserToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenUpdateOne) SaveX(ctx context.Context) *UserToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserToken.owner"`)
	}
	return nil
}

func (_u *UserTokenUpdateOne) sqlSave(ctx context.Context) (_node *UserToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertoken.Table, usertoken.Columns, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertoken.FieldID)
		for _, f := range fields {
			if !usertoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(usertoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebURL(); ok {
		_spec.SetField(usertoken.FieldWebURL, field.TypeString, value)
	}
	if _u.mutation.WebURLCleared() {
		_spec.ClearField(usertoken.FieldWebURL, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(usertoken.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(usertoken.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(usertoken.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastEventID(); ok {
		_spec.SetField(usertoken.FieldLastEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastEventID(); ok {
		_spec.AddField(usertoken.FieldLastEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usertoken.OwnerTable,
			Columns: []string{usertoken.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usertoken.OwnerTable,
			Columns: []string{usertoken.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
