// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pr-reviewer-ai/ent/user"
	"pr-reviewer-ai/ent/usertoken"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTokenCreate is the builder for creating a UserToken entity.
type UserTokenCreate struct {
	config
	mutation *UserTokenMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (_c *UserTokenCreate) SetToken(v string) *UserTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetWebURL sets the "web_url" field.
func (_c *UserTokenCreate) SetWebURL(v string) *UserTokenCreate {
	_c.mutation.SetWebURL(v)
	return _c
}

// SetNillableWebURL sets the "web_url" field if the given value is not nil.
func (_c *UserTokenCreate) SetNillableWebURL(v *string) *UserTokenCreate {
	if v != nil {
		_c.SetWebURL(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *UserTokenCreate) SetProjectID(v int64) *UserTokenCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *UserTokenCreate) SetNillableProjectID(v *int64) *UserTokenCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserTokenCreate) SetUpdatedAt(v time.Time) *UserTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserTokenCreate) SetNillableUpdatedAt(v *time.Time) *UserTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *UserTokenCreate) SetOwnerID(id int) *UserTokenCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *UserTokenCreate) SetOwner(v *User) *UserTokenCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the UserTokenMutation object of the builder.
func (_c *UserTokenCreate) Mutation() *UserTokenMutation {
	return _c.mutation
}

// Save creates the UserToken in the database.
func (_c *UserTokenCreate) Save(ctx context.Context) (*UserToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTokenCreate) SaveX(ctx context.Context) *UserToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTokenCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usertoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTokenCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "UserToken.token"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserToken.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "UserToken.owner"`)}
	}
	return nil
}

func (_c *UserTokenCreate) sqlSave(ctx context.Context) (*UserToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserTokenCreate) createSpec() (*UserToken, *sqlgraph.CreateSpec) {
	var (
		_node = &UserToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usertoken.Table, sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(usertoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.WebURL(); ok {
		_spec.SetField(usertoken.FieldWebURL, field.TypeString, value)
		_node.WebURL = &value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(usertoken.FieldProjectID, field.TypeInt64, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usertoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usertoken.OwnerTable,
			Columns: []string{usertoken.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserTokenCreateBulk is the builder for creating many UserToken entities in bulk.
type UserTokenCreateBulk struct {
	config
	err      error
	builders []*UserTokenCreate
}

// Save creates the UserToken entities in the database.
func (_c *UserTokenCreateBulk) Save(ctx context.Context) ([]*UserToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTokenCreateBulk) SaveX(ctx context.Context) []*UserToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
