// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pr-reviewer-ai/ent/user"
	"pr-reviewer-ai/ent/usertoken"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserToken is the model entity for the UserToken schema.
type UserToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// WebURL holds the value of the "web_url" field.
	WebURL *string `json:"web_url,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID *int64 `json:"project_id,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTokenQuery when eager-loading is set.
	Edges        UserTokenEdges `json:"edges"`
	user_id      *int
	selectValues sql.SelectValues
}

// UserTokenEdges holds the relations/edges for other nodes in the graph.
type UserTokenEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTokenEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertoken.FieldID, usertoken.FieldProjectID:
			values[i] = new(sql.NullInt64)
		case usertoken.FieldToken, usertoken.FieldWebURL:
			values[i] = new(sql.NullString)
		case usertoken.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case usertoken.ForeignKeys[0]: // user_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserToken fields.
func (_m *UserToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usertoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case usertoken.FieldWebURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field web_url", values[i])
			} else if value.Valid {
				_m.WebURL = new(string)
				*_m.WebURL = value.String
			}
		case usertoken.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = new(int64)
				*_m.ProjectID = value.Int64
			}
		case usertoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usertoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_id", value)
			} else if value.Valid {
				_m.user_id = new(int)
				*_m.user_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserToken.
// This includes values selected through modifiers, order, etc.
func (_m *UserToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the UserToken entity.
func (_m *UserToken) QueryOwner() *UserQuery {
	return NewUserTokenClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this UserToken.
// Note that you need to call UserToken.Unwrap() before calling this method if this UserToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserToken) Update() *UserTokenUpdateOne {
	return NewUserTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserToken) Unwrap() *UserToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserToken) String() string {
	var builder strings.Builder
	builder.WriteString("UserToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	if v := _m.WebURL; v != nil {
		builder.WriteString("web_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProjectID; v != nil {
		builder.WriteString("project_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserTokens is a parsable slice of UserToken.
type UserTokens []*UserToken
