// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pr-reviewer-ai/ent/predicate"
	"pr-reviewer-ai/ent/reviewlog"
	"pr-reviewer-ai/ent/user"
	"pr-reviewer-ai/ent/usertoken"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *UserUpdate) ClearPassword() *UserUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetGitlabUserID sets the "gitlab_user_id" field.
func (_u *UserUpdate) SetGitlabUserID(v int) *UserUpdate {
	_u.mutation.ResetGitlabUserID()
	_u.mutation.SetGitlabUserID(v)
	return _u
}

// SetNillableGitlabUserID sets the "gitlab_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGitlabUserID(v *int) *UserUpdate {
	if v != nil {
		_u.SetGitlabUserID(*v)
	}
	return _u
}

// AddGitlabUserID adds value to the "gitlab_user_id" field.
func (_u *UserUpdate) AddGitlabUserID(v int) *UserUpdate {
	_u.mutation.AddGitlabUserID(v)
	return _u
}

// ClearGitlabUserID clears the value of the "gitlab_user_id" field.
func (_u *UserUpdate) ClearGitlabUserID() *UserUpdate {
	_u.mutation.ClearGitlabUserID()
	return _u
}

// SetTokenID sets the "token" edge to the UserToken entity by ID.
func (_u *UserUpdate) SetTokenID(id int) *UserUpdate {
	_u.mutation.SetTokenID(id)
	return _u
}

// SetNillableTokenID sets the "token" edge to the UserToken entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableTokenID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetTokenID(*id)
	}
	return _u
}

// SetToken sets the "token" edge to the UserToken entity.
func (_u *UserUpdate) SetToken(v *UserToken) *UserUpdate {
	return _u.SetTokenID(v.ID)
}

// AddReviewLogIDs adds the "review_logs" edge to the ReviewLog entity by IDs.
func (_u *UserUpdate) AddReviewLogIDs(ids ...int) *UserUpdate {
	_u.mutation.AddReviewLogIDs(ids...)
	return _u
}

// AddReviewLogs adds the "review_logs" edges to the ReviewLog entity.
func (_u *UserUpdate) AddReviewLogs(v ...*ReviewLog) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewLogIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearToken clears the "token" edge to the UserToken entity.
func (_u *UserUpdate) ClearToken() *UserUpdate {
	_u.mutation.ClearToken()
	return _u
}

// ClearReviewLogs clears all "review_logs" edges to the ReviewLog entity.
func (_u *UserUpdate) ClearReviewLogs() *UserUpdate {
	_u.mutation.ClearReviewLogs()
	return _u
}

// RemoveReviewLogIDs removes the "review_logs" edge to ReviewLog entities by IDs.
func (_u *UserUpdate) RemoveReviewLogIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveReviewLogIDs(ids...)
	return _u
}

// RemoveReviewLogs removes "review_logs" edges to ReviewLog entities.
func (_u *UserUpdate) RemoveReviewLogs(v ...*ReviewLog) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.GitlabUserID(); ok {
		_spec.SetField(user.FieldGitlabUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGitlabUserID(); ok {
		_spec.AddField(user.FieldGitlabUserID, field.TypeInt, value)
	}
	if _u.mutation.GitlabUserIDCleared() {
		_spec.ClearField(user.FieldGitlabUserID, field.TypeInt)
	}
	if _u.mutation.TokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.TokenTable,
			Columns: []string{user.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.TokenTable,
			Columns: []string{user.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewLogsIDs(); len(nodes) > 0 && !_u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *UserUpdateOne) ClearPassword() *UserUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetGitlabUserID sets the "gitlab_user_id" field.
func (_u *UserUpdateOne) SetGitlabUserID(v int) *UserUpdateOne {
	_u.mutation.ResetGitlabUserID()
	_u.mutation.SetGitlabUserID(v)
	return _u
}

// SetNillableGitlabUserID sets the "gitlab_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGitlabUserID(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetGitlabUserID(*v)
	}
	return _u
}

// AddGitlabUserID adds value to the "gitlab_user_id" field.
func (_u *UserUpdateOne) AddGitlabUserID(v int) *UserUpdateOne {
	_u.mutation.AddGitlabUserID(v)
	return _u
}

// ClearGitlabUserID clears the value of the "gitlab_user_id" field.
func (_u *UserUpdateOne) ClearGitlabUserID() *UserUpdateOne {
	_u.mutation.ClearGitlabUserID()
	return _u
}

// SetTokenID sets the "token" edge to the UserToken entity by ID.
func (_u *UserUpdateOne) SetTokenID(id int) *UserUpdateOne {
	_u.mutation.SetTokenID(id)
	return _u
}

// SetNillableTokenID sets the "token" edge to the UserToken entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTokenID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetTokenID(*id)
	}
	return _u
}

// SetToken sets the "token" edge to the UserToken entity.
func (_u *UserUpdateOne) SetToken(v *UserToken) *UserUpdateOne {
	return _u.SetTokenID(v.ID)
}

// AddReviewLogIDs adds the "review_logs" edge to the ReviewLog entity by IDs.
func (_u *UserUpdateOne) AddReviewLogIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddReviewLogIDs(ids...)
	return _u
}

// AddReviewLogs adds the "review_logs" edges to the ReviewLog entity.
func (_u *UserUpdateOne) AddReviewLogs(v ...*ReviewLog) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewLogIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearToken clears the "token" edge to the UserToken entity.
func (_u *UserUpdateOne) ClearToken() *UserUpdateOne {
	_u.mutation.ClearToken()
	return _u
}

// ClearReviewLogs clears all "review_logs" edges to the ReviewLog entity.
func (_u *UserUpdateOne) ClearReviewLogs() *UserUpdateOne {
	_u.mutation.ClearReviewLogs()
	return _u
}

// RemoveReviewLogIDs removes the "review_logs" edge to ReviewLog entities by IDs.
func (_u *UserUpdateOne) RemoveReviewLogIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveReviewLogIDs(ids...)
	return _u
}

// RemoveReviewLogs removes "review_logs" edges to ReviewLog entities.
func (_u *UserUpdateOne) RemoveReviewLogs(v ...*ReviewLog) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewLogIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.GitlabUserID(); ok {
		_spec.SetField(user.FieldGitlabUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGitlabUserID(); ok {
		_spec.AddField(user.FieldGitlabUserID, field.TypeInt, value)
	}
	if _u.mutation.GitlabUserIDCleared() {
		_spec.ClearField(user.FieldGitlabUserID, field.TypeInt)
	}
	if _u.mutation.TokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.TokenTable,
			Columns: []string{user.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.TokenTable,
			Columns: []string{user.TokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewLogsIDs(); len(nodes) > 0 && !_u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewLogsTable,
			Columns: []string{user.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
