// Code generated by ent, DO NOT EDIT.

package reviewlog

import (
	"pr-reviewer-ai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldID, id))
}

// MrID applies equality check predicate on the "mr_id" field. It's identical to MrIDEQ.
func MrID(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldMrID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldProjectID, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldComment, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldReviewedAt, v))
}

// MrIDEQ applies the EQ predicate on the "mr_id" field.
func MrIDEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldMrID, v))
}

// MrIDNEQ applies the NEQ predicate on the "mr_id" field.
func MrIDNEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldMrID, v))
}

// MrIDIn applies the In predicate on the "mr_id" field.
func MrIDIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldMrID, vs...))
}

// MrIDNotIn applies the NotIn predicate on the "mr_id" field.
func MrIDNotIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldMrID, vs...))
}

// MrIDGT applies the GT predicate on the "mr_id" field.
func MrIDGT(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldMrID, v))
}

// MrIDGTE applies the GTE predicate on the "mr_id" field.
func MrIDGTE(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldMrID, v))
}

// MrIDLT applies the LT predicate on the "mr_id" field.
func MrIDLT(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldMrID, v))
}

// MrIDLTE applies the LTE predicate on the "mr_id" field.
func MrIDLTE(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldMrID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContainsFold(FieldProjectID, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasSuffix(FieldComment, v))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContainsFold(FieldComment, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldReviewedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.NotPredicates(p))
}
