// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ReviewLog is the predicate function for reviewlog builders.
type ReviewLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserToken is the predicate function for usertoken builders.
type UserToken func(*sql.Selector)
